import type { Paper } from './model';
let token='';
export async function connect():Promise<{token:string;dataDir:string;notesDir:string;extensionDir:string}>{const response=await fetch('/api/session');if(!response.ok)throw Error('Refhaven library service is unavailable. Start Refhaven and try again.');const session=await response.json();token=session.token;return session;}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});if(!response.ok){let message=`Request failed (${response.status})`;try{const data=await response.json();message=data.error||message;}catch{}throw Object.assign(new Error(message),{status:response.status});}if(response.status===204)return undefined as T;return response.json();}
export const loadLibrary=()=>api<{papers:Paper[];collections:string[];revision:number}>('/api/library');
export const writeLibrary=(papers:Paper[],revision:number)=>api<{papers:Paper[];collections:string[];revision:number}>('/api/library',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({papers,revision})});
export async function uploadPdf(file:File,onProgress?:(percent:number)=>void):Promise<{pdfId:string;pdfName:string;size:number}>{
 if(await file.slice(0,5).text()!=='%PDF-')throw Error(`${file.name} is not a PDF.`);
 return new Promise((resolve,reject)=>{const request=new XMLHttpRequest();request.open('POST','/api/pdfs');request.setRequestHeader('Authorization',`Bearer ${token}`);request.setRequestHeader('Content-Type','application/pdf');request.setRequestHeader('X-Folio-Filename',encodeURIComponent(file.name));request.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(Math.round(e.loaded/e.total*100));};request.onerror=()=>reject(Error('PDF upload interrupted. Check that Refhaven is running.'));request.onload=()=>{try{const data=JSON.parse(request.responseText);if(request.status>=200&&request.status<300)resolve(data);else reject(Error(data.error||'Could not store PDF.'));}catch{reject(Error('Invalid response from library service.'));}};request.send(file);});
}
export function download(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export async function downloadApi(path:string,init:RequestInit,name:string){const response=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});if(!response.ok){const error=await response.json();throw Error(error.error||'Document generation failed.');}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
